### ISSUE TITLE
Add support for environment variables.

### ISSUE THREAD

**Issue by lotyp** [buggregator/trap#61]
It would be good to have ability to use TRAP_* env variables to configure /vendor/bin/trap

For example:

```
TRAP_SENDERS=console,server
TRAP_DEBUG_PORTS=9912,xxxx,yyyy
TRAP_UI_PORT=8000
```

Which would simplify usage in docker, here is current example:

```
  trap:
    image: wayofdev/php-dev:8.3-cli-alpine-latest
    container_name: ${COMPOSE_PROJECT_NAME}-trap
    restart: on-failure
    networks:
      - default
    ports:
      - '${TRAP_PORT:-9912}:9912'
      - '${TRAP_UI_PORT:-8000}:8000'
    volumes:
      - ./:/app:rw
      - ~/.composer:/.composer
    env_file:
      - .env
    entrypoint:
      - /app/vendor/bin/trap
      - --ui
      - --port=${TRAP_PORT:-9912}
      - --sender=server
      - --sender=console
```
